#!/usr/bin/env python3
import sys, subprocess, tempfile, os

real_cc = sys.argv[1]
args = sys.argv[2:]

new_args = []
bmi_dir = None

for a in args:
    new_args.append(a)
    if a.endswith('.a'):
        lib = os.path.abspath(a)                      
        t = subprocess.run(['ar', 't', lib], capture_output=True, text=True)
        for m in t.stdout.splitlines():
            if not m.endswith('.o') and not m.startswith('__'):
                if bmi_dir is None:
                    bmi_dir = tempfile.mkdtemp()
                subprocess.run(['ar', 'x', lib, m], cwd=bmi_dir)
                subprocess.run([real_cc, '-std=c++20', '--precompile',
                                f'{bmi_dir}/{m}', '-o',
                                f'{bmi_dir}/{os.path.splitext(m)[0]}.pcm'])

if bmi_dir:
    new_args.insert(0, f'-fprebuilt-module-path={bmi_dir}')

os.execvp(real_cc, [real_cc] + new_args)
